[package]
name = "komorebi-bar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
komorebi-client = { path = "../komorebi-client" }

anyhow = "1"
catppuccin-egui = { version = "5.1", default-features = false, features = ["egui28"] }
chrono = "0.4"
crossbeam-channel = "0.5"
eframe = "0.28"
font-loader = "0.11"
image = "0.25"
netdev = "0.30"
serde_json = "1"
starship-battery = "0.10"
sysinfo = "0.31"
windows = { workspace = true }
windows-icons = "0.1"
egui-phosphor = "0.6.0"