[package]
name = "komorebi-bar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
komorebi-client = { path = "../komorebi-client" }

anyhow = "1"
chrono = "0.4"
eframe = "0.28"
netdev = "0.30"
serde_json = "1"
starship-battery = "0.9"
sysinfo = "0.31"
crossbeam-channel = "0.5"
windows = { workspace = true }